<?php
/**
 * @author Alan Barber <alan@cadence-labs.com>
 * @var \Cadence\Heimdall\Block\Adminhtml\Secret $this
 */
// @codingStandardsIgnoreFile

?>
<style>
    .heimdall .secret-section {
        margin-top:20px;
    }
    .heimdall .secret-human {
        font-size:10px;
    }
</style>
<form method="post" action="<?php echo $this->getSecretUrl() ?>" id="login-form" data-mage-init='{"form": {}, "validation": {}}' autocomplete="off" class="heimdall">
    <fieldset class="admin__fieldset">
        <input type="hidden" name="verification[secret]" value="<?php echo $this->getSecret() ?>" />
        <legend class="admin__legend">
            <span><?php /* @escapeNotVerified */ echo __('Setup Multi-Factor Authentication') ?></span>
        </legend><br/>
        <div>
            <p>
                <?php echo __("Looks like you have not connected your mobile device to your admin account.") ?>
            </p>
            <p>
                <?php echo __("Please follow the instructions below to download Google Authenticator for you mobile device:") ?>
            </p>
        </div>
        <div>
            <p>
                <a href="https://support.google.com/accounts/answer/1066447?hl=en" target="_blank">View Installation Instructions</a>
            </p>
        </div>
        <div class="secret-section">
            <p>
                <?php echo __("Once you've installed Google Authenticator, use the QR code below to sync your mobile device") ?>
            </p>
        </div>
        <div class="secret-section">
            <div class="secret-qr-image">
                <img src="<?php echo $this->getQrCode() ?>" />
            </div>
            <div class="secret-human">
                <pre><?php echo $this->getHumanSecret() ?></pre>
            </div>
        </div>
        <div class="secret-section">
            <p>
                <?php echo __("Finally, please enter the verification code from your mobile device here") ?>
            </p>
        </div>
        <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
        <div class="admin__field _required field-username">
            <label for="secret" class="admin__field-label">
                <span><?php echo __('Secret Code') ?></span>
            </label>
            <div class="admin__field-control">
                <input id="verification_code"
                       class="admin__control-text"
                       type="text"
                       name="verification[code]"
                       autofocus
                       value=""
                       data-validate="{required:true}"
                       placeholder="<?php /* @escapeNotVerified */ echo __('user name') ?>"
                       autocomplete="off"
                />
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
        <div class="form-actions">
            <?php echo $block->getChildHtml('form.buttons'); ?>
        </div>
    </fieldset>
</form>
