<?php
/**
 * @author Alan Barber <alan@cadence-labs.com>
 * @var \Cadence\Heimdall\Block\Adminhtml\Secret $this
 */
// @codingStandardsIgnoreFile

?>
<style>
    .heimdall .secret-section {
        margin-top:20px;
    }
    .heimdall .secret-human {
        font-size:10px;
    }
    .heimdall #remember {
        position:relative;
        top:1px;
        margin-right:5px;
    }
</style>
<form method="post" action="<?php echo $this->getSecretUrl('refresh') ?>" id="login-form" data-mage-init='{"form": {}, "validation": {}}' autocomplete="off" class="heimdall">
    <fieldset class="admin__fieldset">
        <legend class="admin__legend">
            <span><?php /* @escapeNotVerified */ echo __('Verify Multi-Factor Authentication') ?></span>
        </legend><br/>
        <div>
            <p>
                <?php echo __("We don't recognize the device you're logging in with.") ?>
            </p>
        </div>
        <div class="secret-section">
            <p>
                <?php echo __("Please enter a verification code from your connected mobile device in the field below:") ?>
            </p>
        </div>
        <div class="secret-section">

        </div>
        <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
        <div class="admin__field _required field-username">
            <label for="secret" class="admin__field-label">
                <span><?php echo __('Secret Code') ?></span>
            </label>
            <div class="admin__field-control">
                <input id="verification_code"
                       class="admin__control-text"
                       type="text"
                       name="verification[code]"
                       autofocus
                       value=""
                       data-validate="{required:true}"
                       placeholder="<?php /* @escapeNotVerified */ echo __('user name') ?>"
                       autocomplete="off"
                />
            </div>
        </div>
        <div class="admin__field field-remember">
            <label for="remember" class="admin__field-label">
                <input id="remember"
                       class=""
                       type="checkbox"
                       name="verification[remember]"
                       value="1" /> <?php echo __("Remember this device?") ?>
            </label>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
        <div class="form-actions">
            <?php echo $block->getChildHtml('form.buttons'); ?>
        </div>
    </fieldset>
</form>
